[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
allowCrash = false
autoscaling = true

[environment]
NODE_ENV = "production"