[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
allowCrash = false

[environment]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"